let session={tipo:null,login:null,senha:null}; let matches=[]; let myBets=[];
function show(m){const e=document.getElementById('msg');e.textContent=m;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),7000)}
async function api(url, data){let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return await r.json()}
async function loadJogos(){let r=await fetch('/api/jogos');let d=await r.json();matches=d.matches;render();renderAdmin(d.standings)}
async function criarUsuario(){let d=await api('/api/criar-usuario',{nome:novoNome.value,login:novoLogin.value,password:novaSenha.value});show(d.ok?d.mensagem:d.erro||d.mensagem)}
async function entrar(){let d=await api('/api/login',{login:login.value,password:senha.value}); if(!d.ok){show(d.mensagem||d.erro);return} session={tipo:d.tipo,login:login.value.trim().toLowerCase(),senha:senha.value}; document.getElementById('auth').classList.add('hidden'); document.getElementById('session').classList.remove('hidden'); who.textContent=(d.tipo==='admin'?'Administrador: ':'Participante: ')+session.login; if(d.tipo==='admin'){adminArea.classList.remove('hidden')}else{userArea.classList.remove('hidden'); await loadApostas()} await loadJogos(); show(d.mensagem)}
function sair(){session={};location.reload()}
async function loadApostas(){let r=await fetch('/api/apostas/'+encodeURIComponent(session.login));let d=await r.json();myBets=d.bets||[]}
function betFor(id){return myBets.find(b=>b.match_id==id)}
function locked(m){let kick=new Date(m.kickoff);return new Date()>=new Date(kick.getTime()-5*60000)}
function dt(s){return new Date(s).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function localJogo(m){return `${m.stadium||'Estádio a definir'} • ${m.city||''}`.replace(/ • $/,'')}
function horarioJogo(m){return `${dt(m.kickoff)} — horário de Brasília`}
function render(){if(session.tipo==='usuario')renderUser(); if(session.tipo==='admin')renderAdminGames()}
function renderUser(){games.innerHTML=matches.map(m=>{let b=betFor(m.id)||{};let l=locked(m);return `<div class="game ${l?'locked':''}"><small>Grupo ${m.group} • Jogo ${m.id}</small><div class="game-info">🕒 ${horarioJogo(m)}<br>🏟️ ${localJogo(m)}</div><div class="scoreline"><span class="right">${m.home}</span><input id="bh${m.id}" type="number" min="0" value="${b.home??''}" ${l?'disabled':''}><b>x</b><input id="ba${m.id}" type="number" min="0" value="${b.away??''}" ${l?'disabled':''}><span>${m.away}</span></div>${l?'<p><b>Bloqueado</b> — faltam menos de 5 minutos ou o jogo já começou.</p>':`<button onclick="apostar(${m.id})">Salvar aposta</button>`}${b.updated?`<p class="muted">Última alteração: ${b.updated}</p>`:''}</div>`}).join('')}
async function apostar(id){let bh=document.getElementById('bh'+id).value, ba=document.getElementById('ba'+id).value;if(bh===''||ba===''){show('Informe os dois placares.');return}let d=await api('/api/apostar',{login:session.login,password:session.senha,match_id:id,bet_home:bh,bet_away:ba});show(d.ok?d.mensagem:d.erro);await loadApostas();renderUser()}
function renderAdminGames(){adminGames.innerHTML=matches.map(m=>`<div class="game"><small>Grupo ${m.group} • Jogo ${m.id}</small><div class="game-info">🏟️ ${localJogo(m)}</div><input id="ko${m.id}" type="datetime-local" value="${m.kickoff}"><div class="scoreline"><span class="right">${m.home}</span><input id="hg${m.id}" type="number" min="0" value="${m.hg??''}"><b>x</b><input id="ag${m.id}" type="number" min="0" value="${m.ag??''}"><span>${m.away}</span></div></div>`).join('')}
async function salvarResultados(){matches=matches.map(m=>({...m,kickoff:document.getElementById('ko'+m.id).value,hg:val('hg'+m.id),ag:val('ag'+m.id)}));let d=await api('/api/admin/salvar-resultados',{admin_user:session.login,admin_pass:session.senha,matches});show(d.ok?d.mensagem:d.erro);await loadJogos()}
function val(id){let v=document.getElementById(id).value;return v===''?null:Number(v)}
function renderAdmin(standings){if(session.tipo!=='admin'||!standings)return;document.getElementById('standings').innerHTML=Object.entries(standings).map(([g,rows])=>`<div><h3>Grupo ${g}</h3><table><tr><th>Seleção</th><th>Pts</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GP</th><th>GC</th><th>SG</th></tr>${rows.map(r=>`<tr><td>${r['Seleção']}</td><td>${r.Pts}</td><td>${r.J}</td><td>${r.V}</td><td>${r.E}</td><td>${r.D}</td><td>${r.GP}</td><td>${r.GC}</td><td>${r.SG}</td></tr>`).join('')}</table></div>`).join('')}
